/* ============================================================
   data.js  —  勢力・年代データ（画面処理から独立）
   ------------------------------------------------------------
   ここだけ編集すれば内容を増やせます。
   ・CLANS : 勢力の静的情報（名前・色・家紋）
   ・YEARS : 年代ごとの「国→勢力」と勢力の当時の情報
   owners に書かれていない国は自動的に 'other'（その他の諸勢力）
   ============================================================ */

window.SENGOKU_CLANS = {
  takeda:    { name: '武田家',    color: '#c0392b', kamon: 'takeda' },
  uesugi:    { name: '上杉家',    color: '#2f9e8f', kamon: 'uesugi' },
  hojo:      { name: '北条家',    color: '#8296cc', kamon: 'hojo' },
  date:      { name: '伊達家',    color: '#3f6ea8', kamon: 'date' },
  tokugawa:  { name: '徳川家',    color: '#d9b13b', kamon: 'tokugawa' },
  oda:       { name: '織田家',    color: '#e07b2c', kamon: 'oda' },
  mori:      { name: '毛利家',    color: '#7b52a8', kamon: 'mori' },
  chosokabe: { name: '長宗我部家',color: '#6f9e46', kamon: 'chosokabe' },
  shimazu:   { name: '島津家',    color: '#b34a3a', kamon: 'shimazu' },
  imagawa:   { name: '今川家',    color: '#46a8b5', kamon: 'imagawa' },
  saito:     { name: '斎藤家',    color: '#8f9b3a', kamon: 'saito' },
  miyoshi:   { name: '三好家',    color: '#c05f8c', kamon: 'miyoshi' },
  ouchi:     { name: '大内家',    color: '#8c6239', kamon: 'ouchi' },
  amago:     { name: '尼子家',    color: '#5a5fa8', kamon: 'amago' },
  otomo:     { name: '大友家',    color: '#2f7a4f', kamon: 'otomo' },
  ryuzoji:   { name: '龍造寺家',  color: '#b58c5a', kamon: 'ryuzoji' },
  toyotomi:  { name: '豊臣家',    color: '#9b2d5e', kamon: 'toyotomi' },
  maeda:     { name: '前田家',    color: '#c46a9e', kamon: 'maeda' },
  nanbu:     { name: '南部家',    color: '#4f4f7a', kamon: 'nanbu' },
  mogami:    { name: '最上家',    color: '#5b8fa8', kamon: 'mogami' },
  satake:    { name: '佐竹家',    color: '#7d9a35', kamon: 'satake' },
  asakura:   { name: '朝倉家',    color: '#4f7d8f', kamon: 'asakura' },
  rokkaku:   { name: '六角家',    color: '#9c6b4f', kamon: 'rokkaku' },
  ikko:      { name: '加賀一向一揆', color: '#8e5572', kamon: 'ikko' },
  other:     { name: 'その他の諸勢力', color: '#8d8778', kamon: 'other' }
};

/* 共通で使う城の座標（経度・緯度） */
var C = {
  sanpe:   { name: '三戸城',      lon: 141.15, lat: 40.38 },
  morioka: { name: '盛岡城',      lon: 141.15, lat: 39.70 },
  yonezawa:{ name: '米沢城',      lon: 140.12, lat: 37.91 },
  sendai:  { name: '仙台城',      lon: 140.87, lat: 38.27 },
  yamagata:{ name: '山形城',      lon: 140.34, lat: 38.25 },
  kasugayama:{ name: '春日山城',  lon: 138.24, lat: 37.15 },
  aizu:    { name: '会津若松城',  lon: 139.93, lat: 37.49 },
  tsutsuji:{ name: '躑躅ヶ崎館',  lon: 138.57, lat: 35.66 },
  odawara: { name: '小田原城',    lon: 139.15, lat: 35.25 },
  okazaki: { name: '岡崎城',      lon: 137.16, lat: 34.95 },
  hamamatsu:{ name: '浜松城',     lon: 137.73, lat: 34.71 },
  edo:     { name: '江戸城',      lon: 139.76, lat: 35.68 },
  kiyosu:  { name: '清洲城',      lon: 136.85, lat: 35.20 },
  azuchi:  { name: '安土城',      lon: 136.14, lat: 35.15 },
  inabayama:{ name: '稲葉山城',   lon: 136.78, lat: 35.43 },
  kannonji:{ name: '観音寺城',    lon: 136.15, lat: 35.13 },
  ichijodani:{ name: '一乗谷',    lon: 136.31, lat: 35.98 },
  oyama:   { name: '尾山御坊',    lon: 136.66, lat: 36.56 },
  kanazawa:{ name: '金沢城',      lon: 136.66, lat: 36.56 },
  iimoriyama:{ name: '飯盛山城',  lon: 135.64, lat: 34.72 },
  osaka:   { name: '大坂城',      lon: 135.50, lat: 34.69 },
  sunpu:   { name: '駿府館',      lon: 138.38, lat: 34.98 },
  yamaguchi:{ name: '山口館',     lon: 131.47, lat: 34.18 },
  gassan:  { name: '月山富田城',  lon: 133.20, lat: 35.28 },
  koriyama:{ name: '吉田郡山城',  lon: 132.70, lat: 34.67 },
  hiroshima:{ name: '広島城',     lon: 132.46, lat: 34.40 },
  oko:     { name: '岡豊城',      lon: 133.62, lat: 33.60 },
  uchijo:  { name: '内城(鹿児島)',lon: 130.55, lat: 31.60 },
  funai:   { name: '府内館',      lon: 131.61, lat: 33.24 },
  muranaka:{ name: '村中城(佐賀)',lon: 130.30, lat: 33.25 },
  ota:     { name: '太田城',      lon: 140.53, lat: 36.54 }
};

window.SENGOKU_YEARS = [
  /* ========================= 1550年 ========================= */
  {
    year: 1550, era: '天文19年', note: '三好長慶が畿内を握った頃',
    owners: {
      mutsu:'nanbu', nanou:'date', dewa:'mogami',
      echigo:'uesugi', sado:'uesugi', echizen:'asakura', kaga:'ikko',
      kai:'takeda', hitachi:'satake',
      musashi:'hojo', sagami:'hojo', izu:'hojo', shimousa:'hojo',
      suruga:'imagawa', totomi:'imagawa', mikawa:'imagawa',
      owari:'oda', mino:'saito', omi:'rokkaku',
      yamashiro:'miyoshi', kawachi:'miyoshi', izumi:'miyoshi', settsu:'miyoshi',
      awaji:'miyoshi', awa_s:'miyoshi', sanuki:'miyoshi',
      hoki:'amago', izumo:'amago', iwami:'amago', mimasaka:'amago',
      aki:'mori', bingo:'ouchi', suo:'ouchi', nagato:'ouchi',
      chikuzen:'ouchi', buzen:'ouchi',
      chikugo:'otomo', bungo:'otomo', hizen:'ryuzoji',
      tosa:'chosokabe', osumi:'shimazu', satsuma:'shimazu'
    },
    clans: {
      nanbu:   { head:'南部晴政', castle:C.sanpe, lands:'陸奥北部', retainers:['北信愛','南部政康','石川高信'], power:2,
                 events:['三戸を本拠に糠部一帯を支配'], desc:'陸奥北端の名族。九戸氏ら一族との緊張を抱えつつ北奥州に君臨した。' },
      date:    { head:'伊達晴宗', castle:C.yonezawa, lands:'出羽置賜・南奥州', retainers:['中野宗時','牧野久仲','桑折景長'], power:3,
                 events:['天文の乱の後、米沢を本拠に家中を再編'], desc:'父・稙宗との内乱(天文の乱)を制し、米沢に本拠を移した。' },
      mogami:  { head:'最上義守', castle:C.yamagata, lands:'出羽村山・最上', retainers:['氏家定直','中野義時'], power:2,
                 events:['伊達氏の影響下で家勢を保つ'], desc:'出羽の内陸を押さえる名門斯波氏の分流。' },
      uesugi:  { head:'長尾景虎(のちの上杉謙信)', castle:C.kasugayama, lands:'越後・佐渡', retainers:['直江実綱','柿崎景家','本庄実乃'], power:3,
                 events:['守護代として越後の内乱を鎮めつつある'], desc:'21歳の景虎が越後統一へ向けて動き出した頃。' },
      asakura: { head:'朝倉義景', castle:C.ichijodani, lands:'越前', retainers:['朝倉景鏡','朝倉宗滴'], power:3,
                 events:['一乗谷に京風の文化が花開く'], desc:'一向一揆と対峙しつつ北陸に独自の文化圏を築いた。' },
      ikko:    { head:'本願寺証如(門徒衆)', castle:C.oyama, lands:'加賀', retainers:['七里頼周','超勝寺'], power:2,
                 events:['「百姓の持ちたる国」として加賀を自治'], desc:'守護富樫氏を倒した門徒による自治が続いていた。' },
      takeda:  { head:'武田晴信(信玄)', castle:C.tsutsuji, lands:'甲斐・信濃の一部', retainers:['板垣信方','甘利虎泰','飯富虎昌'], power:3,
                 events:['砥石崩れで村上義清に大敗'], desc:'信濃侵攻の途上。生涯屈指の敗戦を喫した年。' },
      hojo:    { head:'北条氏康', castle:C.odawara, lands:'相模・伊豆・武蔵・下総の一部', retainers:['北条綱成','大道寺政繁','松田憲秀'], power:4,
                 events:['河越夜戦の勝利を経て関東の覇権を固める'], desc:'検地と税制改革で知られる関東の実力者。' },
      imagawa: { head:'今川義元', castle:C.sunpu, lands:'駿河・遠江・三河', retainers:['太原雪斎','朝比奈泰能','岡部元信'], power:4,
                 events:['三河を制圧し、松平氏を従属させる'], desc:'東海一の弓取り。軍師・太原雪斎を擁し全盛期を迎える。' },
      oda:     { head:'織田信秀', castle:C.kiyosu, lands:'尾張の一部', retainers:['平手政秀','林秀貞','織田信長'], power:2,
                 events:['信秀の病が篤く、尾張は分裂状態'], desc:'尾張下四郡の実力者。翌年に信秀が没し信長が家督を継ぐ。' },
      saito:   { head:'斎藤道三', castle:C.inabayama, lands:'美濃', retainers:['斎藤義龍','日根野弘就'], power:3,
                 events:['娘・帰蝶を織田信長に嫁がせ同盟'], desc:'油商人から国主に成り上がったとされる「美濃の蝮」。' },
      rokkaku: { head:'六角定頼', castle:C.kannonji, lands:'近江南部', retainers:['蒲生定秀','後藤賢豊'], power:3,
                 events:['楽市を布き、幕政にも影響力を持つ'], desc:'南近江の守護。楽市の先駆けとされる。' },
      miyoshi: { head:'三好長慶', castle:C.iimoriyama, lands:'摂津・河内・和泉・山城・阿波・讃岐・淡路', retainers:['松永久秀','三好長逸','安宅冬康'], power:5,
                 events:['江口の戦いに勝ち、将軍を京から追う'], desc:'幕府を凌ぐ実権を握った、事実上最初の「天下人」。' },
      amago:   { head:'尼子晴久', castle:C.gassan, lands:'出雲・伯耆・石見・美作', retainers:['尼子国久','宇山久兼'], power:4,
                 events:['新宮党を擁し山陰に覇を唱える'], desc:'月山富田城を拠点に山陰8か国の守護を号した。' },
      mori:    { head:'毛利元就', castle:C.koriyama, lands:'安芸', retainers:['福原貞俊','児玉就忠','桂元澄'], power:2,
                 events:['井上党を粛清し家中の統制を確立'], desc:'まだ安芸一国の国人領主。大内・尼子の間で力を蓄えていた。' },
      ouchi:   { head:'大内義隆', castle:C.yamaguchi, lands:'周防・長門・備後・筑前・豊前', retainers:['陶隆房','杉重矩','相良武任'], power:4,
                 events:['山口に西国一の文化が栄えるが家中は不穏'], desc:'翌年、陶隆房の謀反で滅ぶことになる西国の名門。' },
      otomo:   { head:'大友義鎮(宗麟)', castle:C.funai, lands:'豊後・筑後', retainers:['立花道雪','臼杵鑑速','吉岡長増'], power:3,
                 events:['二階崩れの変で家督を継ぐ'], desc:'南蛮貿易とキリスト教で知られる豊後の太守。この年に当主となった。' },
      ryuzoji: { head:'龍造寺胤栄', castle:C.muranaka, lands:'肥前の一部', retainers:['龍造寺隆信','鍋島清房'], power:1,
                 events:['少弐氏の圧迫を受け苦境にある'], desc:'肥前の国人。後に隆信のもとで急拡大する。' },
      chosokabe:{ head:'長宗我部国親', castle:C.oko, lands:'土佐岡豊周辺', retainers:['長宗我部元親','吉田重俊'], power:1,
                 events:['岡豊城を回復し土佐中央部へ勢力を伸ばす'], desc:'一度は没落した家を再興した。息子が元親。' },
      shimazu: { head:'島津貴久', castle:C.uchijo, lands:'薩摩・大隅の一部', retainers:['島津義久','伊集院忠朗'], power:2,
                 events:['薩摩をほぼ統一し、鉄砲を導入'], desc:'種子島に伝来した鉄砲をいち早く実戦投入した。' },
      satake:  { head:'佐竹義昭', castle:C.ota, lands:'常陸', retainers:['和田昭為','小野崎義昌'], power:2,
                 events:['常陸統一へ向け江戸氏らと抗争'], desc:'源氏の名門。北条・伊達に挟まれ苦しい舵取りが続く。' },
      other:   { head:'—', castle:null, lands:'各地', retainers:[], power:1,
                 events:['大小の国人・寺社勢力が割拠'], desc:'この地図で個別に色分けしていない国人・一揆・寺社などの勢力。' }
    }
  },

  /* ========================= 1560年 ========================= */
  {
    year: 1560, era: '永禄3年', note: '桶狭間の戦いの年',
    owners: {
      mutsu:'nanbu', nanou:'date', dewa:'mogami',
      echigo:'uesugi', sado:'uesugi', kozuke:'uesugi',
      echizen:'asakura', kaga:'ikko',
      kai:'takeda', shinano:'takeda',
      hitachi:'satake',
      musashi:'hojo', sagami:'hojo', izu:'hojo', shimousa:'hojo',
      suruga:'imagawa', totomi:'imagawa', mikawa:'tokugawa',
      owari:'oda', mino:'saito', omi:'rokkaku',
      yamashiro:'miyoshi', yamato:'miyoshi', kawachi:'miyoshi', izumi:'miyoshi',
      settsu:'miyoshi', awaji:'miyoshi', awa_s:'miyoshi', sanuki:'miyoshi',
      hoki:'amago', izumo:'amago', mimasaka:'amago',
      iwami:'mori', bingo:'mori', aki:'mori', suo:'mori', nagato:'mori',
      chikuzen:'otomo', buzen:'otomo', chikugo:'otomo', bungo:'otomo',
      hizen:'ryuzoji', tosa:'chosokabe', osumi:'shimazu', satsuma:'shimazu'
    },
    clans: {
      nanbu:   { head:'南部晴政', castle:C.sanpe, lands:'陸奥北部', retainers:['北信愛','石川高信'], power:2,
                 events:['安東氏と鹿角をめぐり争う'], desc:'北奥州最大の勢力。' },
      date:    { head:'伊達晴宗', castle:C.yonezawa, lands:'出羽置賜・南奥州', retainers:['中野宗時','伊達輝宗'], power:3,
                 events:['奥州探題に任じられる'], desc:'南奥州の盟主として周辺大名と縁組を重ねた。' },
      mogami:  { head:'最上義守', castle:C.yamagata, lands:'出羽村山', retainers:['氏家定直'], power:2,
                 events:['伊達氏との関係を保ちつつ自立を模索'], desc:'のちの義光の父。' },
      uesugi:  { head:'長尾景虎', castle:C.kasugayama, lands:'越後・佐渡・上野', retainers:['直江実綱','柿崎景家','斎藤朝信'], power:4,
                 events:['関東へ出兵し、北条方の諸城を落とす'], desc:'関東管領・上杉憲政を擁して関東へ大遠征。翌年に上杉姓を継ぐ。' },
      asakura: { head:'朝倉義景', castle:C.ichijodani, lands:'越前', retainers:['朝倉景鏡','山崎吉家'], power:3,
                 events:['加賀一向一揆と和睦'], desc:'北陸の名門。' },
      ikko:    { head:'本願寺門徒衆', castle:C.oyama, lands:'加賀', retainers:['七里頼周'], power:2,
                 events:['朝倉氏と一時的に和睦'], desc:'本願寺の指導下にある自治勢力。' },
      takeda:  { head:'武田信玄', castle:C.tsutsuji, lands:'甲斐・信濃', retainers:['馬場信春','山県昌景','高坂昌信'], power:4,
                 events:['信濃をほぼ平定し、川中島で上杉と対峙'], desc:'翌年に第四次川中島の戦いを迎える。' },
      hojo:    { head:'北条氏康', castle:C.odawara, lands:'相模・伊豆・武蔵・下総の一部', retainers:['北条綱成','北条氏政'], power:4,
                 events:['上杉軍の関東侵攻を受け小田原に籠城の構え'], desc:'関東の覇者としての正念場。' },
      imagawa: { head:'今川義元 → 氏真', castle:C.sunpu, lands:'駿河・遠江', retainers:['朝比奈泰朝','岡部元信'], power:3,
                 events:['桶狭間の戦いで義元が討死','氏真が家督を継ぐも動揺広がる'], desc:'上洛を目指した大軍が尾張で崩れ、名門が傾いた年。' },
      tokugawa:{ head:'松平元康(のちの徳川家康)', castle:C.okazaki, lands:'三河', retainers:['酒井忠次','石川数正','本多忠勝'], power:2,
                 events:['桶狭間の後、岡崎城に帰還し今川から自立'], desc:'19歳。人質生活を脱し、独立への一歩を踏み出す。' },
      oda:     { head:'織田信長', castle:C.kiyosu, lands:'尾張', retainers:['柴田勝家','丹羽長秀','佐久間信盛'], power:3,
                 events:['桶狭間の戦いで今川義元を討ち取る'], desc:'兵力差を覆した奇襲で、一躍その名を天下に知らしめた。' },
      saito:   { head:'斎藤義龍', castle:C.inabayama, lands:'美濃', retainers:['竹中重元','日根野弘就'], power:3,
                 events:['父・道三を倒し美濃を掌握、織田と対立'], desc:'翌年に急死し、斎藤氏は急速に傾く。' },
      rokkaku: { head:'六角義賢', castle:C.kannonji, lands:'近江南部', retainers:['蒲生賢秀','後藤賢豊'], power:3,
                 events:['浅井氏の離反に直面'], desc:'南近江の守護。' },
      miyoshi: { head:'三好長慶', castle:C.iimoriyama, lands:'畿内・阿波・讃岐・淡路', retainers:['松永久秀','三好義興','安宅冬康'], power:5,
                 events:['幕府の実権を握り、畿内に強大な政権を築く'], desc:'三好政権の絶頂期。' },
      amago:   { head:'尼子晴久', castle:C.gassan, lands:'出雲・伯耆・美作', retainers:['宇山久兼','本城常光'], power:3,
                 events:['石見銀山をめぐり毛利と争う中、晴久が急死'], desc:'当主の死により尼子は毛利の攻勢に晒される。' },
      mori:    { head:'毛利元就', castle:C.koriyama, lands:'安芸・周防・長門・備後・石見', retainers:['吉川元春','小早川隆景','福原貞俊'], power:5,
                 events:['大内氏を滅ぼし、中国地方の覇者となる'], desc:'厳島の戦いから防長経略へ。両川体制が完成した。' },
      otomo:   { head:'大友宗麟', castle:C.funai, lands:'豊後・筑後・筑前・豊前', retainers:['立花道雪','角隈石宗'], power:4,
                 events:['九州探題に任じられ、北九州を支配'], desc:'大内氏滅亡の後、北九州の権益を継承した。' },
      ryuzoji: { head:'龍造寺隆信', castle:C.muranaka, lands:'肥前の一部', retainers:['鍋島直茂','納富信景'], power:2,
                 events:['一時追放されるも肥前に復帰'], desc:'「肥前の熊」と呼ばれる猛将。' },
      chosokabe:{ head:'長宗我部元親', castle:C.oko, lands:'土佐中部', retainers:['吉良親貞','香宗我部親泰'], power:1,
                 events:['長浜の戦いで初陣を飾る','父・国親が没し家督を継ぐ'], desc:'「姫若子」と侮られた元親の飛躍が始まる。' },
      shimazu: { head:'島津貴久', castle:C.uchijo, lands:'薩摩・大隅の一部', retainers:['島津義久','島津義弘'], power:3,
                 events:['大隅の肝付氏と激しく争う'], desc:'四兄弟が育ちつつあった。' },
      satake:  { head:'佐竹義昭', castle:C.ota, lands:'常陸', retainers:['和田昭為'], power:2,
                 events:['上杉方につき北条と対立'], desc:'常陸の名門。' },
      other:   { head:'—', castle:null, lands:'各地', retainers:[], power:1,
                 events:['国人・一揆勢が各地に割拠'], desc:'個別に色分けしていない諸勢力。' }
    }
  },

  /* ========================= 1575年 ========================= */
  {
    year: 1575, era: '天正3年', note: '長篠の戦いの頃',
    owners: {
      mutsu:'nanbu', nanou:'date', dewa:'mogami',
      echigo:'uesugi', sado:'uesugi', etchu:'uesugi',
      kaga:'ikko', echizen:'oda', wakasa:'oda',
      kai:'takeda', shinano:'takeda', kozuke:'takeda', suruga:'takeda',
      hitachi:'satake',
      musashi:'hojo', sagami:'hojo', izu:'hojo', shimousa:'hojo',
      totomi:'tokugawa', mikawa:'tokugawa',
      owari:'oda', mino:'oda', omi:'oda', ise:'oda', shima:'oda',
      yamashiro:'oda', yamato:'oda', kawachi:'oda', izumi:'oda', settsu:'oda',
      hoki:'mori', izumo:'mori', iwami:'mori', mimasaka:'mori', bizen:'mori',
      bicchu:'mori', bingo:'mori', aki:'mori', suo:'mori', nagato:'mori',
      awa_s:'miyoshi', sanuki:'miyoshi', tosa:'chosokabe',
      chikuzen:'otomo', buzen:'otomo', chikugo:'otomo', bungo:'otomo',
      hizen:'ryuzoji', osumi:'shimazu', satsuma:'shimazu'
    },
    clans: {
      takeda:  { head:'武田勝頼', castle:C.tsutsuji, lands:'甲斐・信濃・駿河・上野の一部', retainers:['山県昌景','馬場信春','内藤昌豊','真田昌幸'], power:4,
                 events:['長篠の戦いで織田・徳川連合軍に大敗','宿老の多くを一挙に失う'], desc:'父・信玄の版図を継ぎ最大領国を得たが、長篠で屋台骨を折られた。' },
      uesugi:  { head:'上杉謙信', castle:C.kasugayama, lands:'越後・佐渡・越中', retainers:['直江景綱','柿崎景家','斎藤朝信'], power:4,
                 events:['越中を平定し、能登・加賀へ進む構え'], desc:'信長包囲網の一角として西へ目を向け始める。' },
      hojo:    { head:'北条氏政', castle:C.odawara, lands:'相模・伊豆・武蔵・下総の一部', retainers:['北条氏照','北条氏邦','松田憲秀'], power:4,
                 events:['武田と同盟し、関東で佐竹・里見と争う'], desc:'甲相同盟のもと関東経営に専念した。' },
      date:    { head:'伊達輝宗', castle:C.yonezawa, lands:'出羽置賜・南奥州', retainers:['遠藤基信','鬼庭良直'], power:3,
                 events:['相馬氏と伊具郡をめぐり抗争'], desc:'政宗の父。織田信長とも音信を通じた外交巧者。' },
      nanbu:   { head:'南部晴政', castle:C.sanpe, lands:'陸奥北部', retainers:['北信愛','九戸政実'], power:2,
                 events:['家督をめぐり一族が対立'], desc:'北奥州の雄。' },
      mogami:  { head:'最上義光', castle:C.yamagata, lands:'出羽村山', retainers:['氏家守棟','鮭延秀綱'], power:2,
                 events:['父・義守と対立し家中が二分'], desc:'謀略に長けた「出羽の驍将」。政宗の伯父にあたる。' },
      tokugawa:{ head:'徳川家康', castle:C.hamamatsu, lands:'三河・遠江', retainers:['酒井忠次','本多忠勝','榊原康政'], power:3,
                 events:['長篠の戦いで織田と共に武田を破る','長篠城の攻防で奥平信昌が奮戦'], desc:'武田の圧迫を耐え抜き、反攻に転じた年。' },
      oda:     { head:'織田信長', castle:C.azuchi, lands:'尾張・美濃・近江・伊勢・畿内・越前', retainers:['柴田勝家','羽柴秀吉','明智光秀','丹羽長秀'], power:5,
                 events:['長篠の戦いで鉄砲を活用し武田軍を撃破','越前一向一揆を平定','家督を信忠に譲る'], desc:'畿内を制圧し、天下布武が現実味を帯びた。翌年から安土築城。' },
      mori:    { head:'毛利輝元', castle:C.koriyama, lands:'安芸・備後・周防・長門・出雲・石見・伯耆ほか', retainers:['吉川元春','小早川隆景','福原貞俊'], power:5,
                 events:['備中・備前へ影響力を広げ、織田と接触'], desc:'祖父・元就の遺産を両川が支える中国地方の巨人。' },
      chosokabe:{ head:'長宗我部元親', castle:C.oko, lands:'土佐', retainers:['吉良親貞','香宗我部親泰','谷忠澄'], power:3,
                 events:['四万十川の戦いで一条氏を破り土佐を統一'], desc:'一領具足を擁し、四国統一へ動き出す。' },
      shimazu: { head:'島津義久', castle:C.uchijo, lands:'薩摩・大隅', retainers:['島津義弘','島津歳久','新納忠元'], power:3,
                 events:['大隅を平定し、三州統一に王手'], desc:'四兄弟の結束で九州南部を制していく。' },
      ikko:    { head:'本願寺門徒衆', castle:C.oyama, lands:'加賀', retainers:['七里頼周'], power:2,
                 events:['越前の一揆が織田軍に壊滅させられる'], desc:'石山本願寺と連動して織田に抵抗を続けた。' },
      satake:  { head:'佐竹義重', castle:C.ota, lands:'常陸', retainers:['和田昭為','梶原政景'], power:3,
                 events:['北条氏と関東で角逐'], desc:'「鬼義重」と恐れられた常陸の当主。' },
      miyoshi: { head:'三好長治', castle:{ name:'勝瑞城', lon:134.53, lat:34.10 }, lands:'阿波・讃岐', retainers:['篠原長房(故)','三好存保'], power:2,
                 events:['家中の内訌が続き、長宗我部の圧力が強まる'], desc:'畿内を失った三好の残存勢力。' },
      otomo:   { head:'大友宗麟', castle:C.funai, lands:'豊後・筑後・筑前・豊前', retainers:['立花道雪','高橋紹運'], power:4,
                 events:['北九州六か国に号令'], desc:'九州最大の勢力として全盛期にあった。' },
      ryuzoji: { head:'龍造寺隆信', castle:C.muranaka, lands:'肥前', retainers:['鍋島直茂','龍造寺四天王'], power:3,
                 events:['肥前をほぼ統一し、筑後へ進出'], desc:'大友の勢力圏を侵食し始める。' },
      other:   { head:'—', castle:null, lands:'各地', retainers:[], power:1,
                 events:['本願寺・雑賀衆・国人らが各地に割拠'], desc:'個別に色分けしていない諸勢力。' }
    }
  },

  /* ========================= 1582年 ========================= */
  {
    year: 1582, era: '天正10年', note: '本能寺の変の年',
    owners: {
      mutsu:'nanbu', nanou:'date', dewa:'mogami',
      echigo:'uesugi', sado:'uesugi',
      etchu:'oda', noto:'oda', kaga:'oda', echizen:'oda', wakasa:'oda',
      shinano:'oda', kai:'oda', hida:'oda', kozuke:'oda',
      omi:'oda', mino:'oda', owari:'oda', ise:'oda', shima:'oda', iga:'oda',
      yamashiro:'oda', yamato:'oda', kawachi:'oda', izumi:'oda', settsu:'oda',
      tanba:'oda', tango:'oda', tajima:'oda', inaba:'oda',
      harima:'oda', bizen:'oda', awaji:'oda',
      suruga:'tokugawa', totomi:'tokugawa', mikawa:'tokugawa',
      hitachi:'satake',
      musashi:'hojo', sagami:'hojo', izu:'hojo', shimousa:'hojo', kazusa:'hojo',
      hoki:'mori', izumo:'mori', iwami:'mori', mimasaka:'mori',
      bicchu:'mori', bingo:'mori', aki:'mori', suo:'mori', nagato:'mori',
      awa_s:'chosokabe', sanuki:'chosokabe', tosa:'chosokabe',
      chikuzen:'otomo', buzen:'otomo', bungo:'otomo',
      chikugo:'ryuzoji', hizen:'ryuzoji',
      higo:'shimazu', hyuga:'shimazu', osumi:'shimazu', satsuma:'shimazu'
    },
    clans: {
      oda:     { head:'織田信長', castle:C.azuchi, lands:'東海・畿内・北陸・山陰・甲信', retainers:['柴田勝家','羽柴秀吉','明智光秀','滝川一益'], power:5,
                 events:['武田氏を滅ぼす(天目山)','本能寺の変で信長・信忠が横死','山崎の戦いで明智光秀が敗死'], desc:'天下統一目前で家臣の謀反により斃れた。図はその直前の版図。' },
      tokugawa:{ head:'徳川家康', castle:C.hamamatsu, lands:'三河・遠江・駿河', retainers:['酒井忠次','本多忠勝','井伊直政'], power:3,
                 events:['武田攻めの功で駿河を得る','伊賀越えで堺から三河へ逃げ帰る','甲斐・信濃へ進出'], desc:'本能寺の報せに窮地へ陥るも、直後に旧武田領へ手を伸ばす。' },
      uesugi:  { head:'上杉景勝', castle:C.kasugayama, lands:'越後・佐渡', retainers:['直江兼続','須田満親'], power:2,
                 events:['魚津城が落城し滅亡寸前','本能寺の変で織田の攻勢が止み九死に一生'], desc:'御館の乱を経て当主となった直後の苦境。' },
      hojo:    { head:'北条氏直', castle:C.odawara, lands:'関東6か国', retainers:['北条氏照','北条氏邦','松田憲秀'], power:4,
                 events:['本能寺の後、滝川一益を神流川で破り上野へ進出'], desc:'関東最大の勢力。氏政が後見。' },
      date:    { head:'伊達輝宗', castle:C.yonezawa, lands:'出羽置賜・南奥州', retainers:['遠藤基信','鬼庭良直','伊達政宗'], power:3,
                 events:['嫡男・政宗が元服し家中を固める'], desc:'翌々年に政宗へ家督を譲る。' },
      nanbu:   { head:'南部信直', castle:C.sanpe, lands:'陸奥北部', retainers:['北信愛','八戸政栄'], power:2,
                 events:['家督を継ぐが九戸政実と対立'], desc:'南部氏の内訌が深まる。' },
      mogami:  { head:'最上義光', castle:C.yamagata, lands:'出羽村山・最上', retainers:['氏家守棟','志村光安'], power:2,
                 events:['庄内・大宝寺氏と争う'], desc:'出羽の切れ者。' },
      mori:    { head:'毛利輝元', castle:C.koriyama, lands:'中国地方西部', retainers:['吉川元春','小早川隆景','清水宗治'], power:4,
                 events:['備中高松城を羽柴秀吉に水攻めされる','本能寺の報を受け秀吉と即時講和'], desc:'織田との決戦寸前に天下が引っくり返った。' },
      chosokabe:{ head:'長宗我部元親', castle:C.oko, lands:'土佐・阿波・讃岐', retainers:['香宗我部親泰','谷忠澄','久武親信'], power:3,
                 events:['中富川の戦いで十河存保を破り阿波を制圧','織田の四国征伐が本能寺で中止となる'], desc:'四国統一に王手。信長の死に救われた。' },
      shimazu: { head:'島津義久', castle:C.uchijo, lands:'薩摩・大隅・日向・肥後', retainers:['島津義弘','島津家久','新納忠元'], power:4,
                 events:['肥後の相良氏を降し、北上を続ける'], desc:'耳川で大友を破って以来、九州制覇へ突き進む。' },
      otomo:   { head:'大友義統', castle:C.funai, lands:'豊後・豊前・筑前の一部', retainers:['立花道雪','高橋紹運'], power:2,
                 events:['島津・龍造寺の圧迫で勢力が縮む'], desc:'耳川の大敗以来、退勢が続く。' },
      ryuzoji: { head:'龍造寺隆信', castle:C.muranaka, lands:'肥前・筑後', retainers:['鍋島直茂','龍造寺政家'], power:3,
                 events:['五州二島の太守を称する'], desc:'九州三強の一角に伸し上がった。' },
      satake:  { head:'佐竹義重', castle:C.ota, lands:'常陸', retainers:['和田昭為','梶原政景'], power:3,
                 events:['北条氏と下野で対峙'], desc:'関東で北条に抗し続けた。' },
      other:   { head:'—', castle:null, lands:'各地', retainers:[], power:1,
                 events:['里見・雑賀衆・国人らが割拠'], desc:'個別に色分けしていない諸勢力。' }
    }
  },

  /* ========================= 1590年 ========================= */
  {
    year: 1590, era: '天正18年', note: '小田原征伐・天下統一',
    owners: {
      mutsu:'nanbu', nanou:'date', dewa:'mogami',
      echigo:'uesugi', sado:'uesugi',
      etchu:'maeda', noto:'maeda', kaga:'maeda',
      musashi:'tokugawa', sagami:'tokugawa', izu:'tokugawa',
      shimousa:'tokugawa', kazusa:'tokugawa', kozuke:'tokugawa',
      hitachi:'satake',
      hoki:'mori', izumo:'mori', iwami:'mori', bingo:'mori',
      aki:'mori', suo:'mori', nagato:'mori', chikuzen:'mori',
      tosa:'chosokabe', bungo:'otomo', hizen:'ryuzoji',
      osumi:'shimazu', satsuma:'shimazu',
      echizen:'toyotomi', wakasa:'toyotomi', shinano:'toyotomi', kai:'toyotomi',
      hida:'toyotomi', shimotsuke:'toyotomi', suruga:'toyotomi', totomi:'toyotomi',
      mikawa:'toyotomi', owari:'toyotomi', mino:'toyotomi', omi:'toyotomi',
      ise:'toyotomi', shima:'toyotomi', iga:'toyotomi',
      yamashiro:'toyotomi', yamato:'toyotomi', kawachi:'toyotomi', izumi:'toyotomi',
      settsu:'toyotomi', kii:'toyotomi', tanba:'toyotomi', tango:'toyotomi',
      tajima:'toyotomi', inaba:'toyotomi', harima:'toyotomi', mimasaka:'toyotomi',
      bizen:'toyotomi', bicchu:'toyotomi', awaji:'toyotomi', awa_s:'toyotomi',
      sanuki:'toyotomi', iyo:'toyotomi', chikugo:'toyotomi', buzen:'toyotomi',
      higo:'toyotomi', hyuga:'toyotomi'
    },
    clans: {
      toyotomi:{ head:'豊臣秀吉', castle:C.osaka, lands:'畿内を中心に全国の蔵入地', retainers:['石田三成','増田長盛','浅野長政','加藤清正'], power:5,
                 events:['小田原征伐で北条氏を滅ぼす','奥州仕置を行い天下統一を完成'], desc:'関白として全国の大名を臣従させ、太閤検地と刀狩を進めた。' },
      tokugawa:{ head:'徳川家康', castle:C.edo, lands:'武蔵・相模・伊豆・上野・上総・下総', retainers:['本多忠勝','井伊直政','榊原康政','本多正信'], power:5,
                 events:['小田原征伐に参陣','旧北条領へ移封され、江戸を本拠とする'], desc:'東海5か国から関東250万石へ。江戸の町づくりが始まった。' },
      date:    { head:'伊達政宗', castle:C.yonezawa, lands:'出羽置賜・南奥州', retainers:['片倉景綱','伊達成実','鬼庭綱元'], power:3,
                 events:['小田原に遅参し秀吉に謝罪','会津を没収され版図が縮む'], desc:'摺上原で蘆名を破り奥州を制した矢先、天下人の登場に屈した。' },
      uesugi:  { head:'上杉景勝', castle:C.kasugayama, lands:'越後・佐渡・出羽庄内', retainers:['直江兼続','須田満親'], power:3,
                 events:['小田原征伐・奥州仕置に従軍'], desc:'豊臣政権の重鎮として遇された。' },
      maeda:   { head:'前田利家', castle:C.kanazawa, lands:'加賀・能登・越中', retainers:['前田利長','村井長頼'], power:4,
                 events:['小田原征伐に従軍','北陸の抑えとして加賀百万石を築く'], desc:'秀吉の盟友。のちの五大老。' },
      mogami:  { head:'最上義光', castle:C.yamagata, lands:'出羽村山・最上', retainers:['氏家守棟','志村光安'], power:2,
                 events:['小田原に参陣し所領を安堵される'], desc:'政宗の伯父。庄内をめぐり上杉と対立していく。' },
      nanbu:   { head:'南部信直', castle:C.sanpe, lands:'陸奥北部', retainers:['北信愛','八戸政栄'], power:2,
                 events:['小田原に参陣し所領を安堵','翌年に九戸政実の乱が起こる'], desc:'豊臣大名として存続。' },
      satake:  { head:'佐竹義宣', castle:C.ota, lands:'常陸', retainers:['和田昭為','梶原政景'], power:3,
                 events:['小田原に参陣し常陸54万石を安堵される'], desc:'石田三成と親しく、のちの関ヶ原で苦境に立つ。' },
      mori:    { head:'毛利輝元', castle:C.hiroshima, lands:'安芸ほか中国8か国', retainers:['吉川広家','小早川隆景','安国寺恵瓊'], power:5,
                 events:['広島城の築城を開始','小早川隆景が筑前を治める'], desc:'五大老の一人。112万石の大身。' },
      chosokabe:{ head:'長宗我部元親', castle:{ name:'浦戸城', lon:133.55, lat:33.50 }, lands:'土佐', retainers:['香宗我部親泰','谷忠澄'], power:2,
                 events:['小田原征伐に水軍を率いて従軍'], desc:'四国平定で土佐一国に減らされ、豊臣大名となった。' },
      shimazu: { head:'島津義久', castle:C.uchijo, lands:'薩摩・大隅', retainers:['島津義弘','伊集院忠棟'], power:3,
                 events:['豊臣政権下で薩摩・大隅を安堵される'], desc:'九州平定で降伏し、南九州に押し戻された。' },
      otomo:   { head:'大友義統', castle:C.funai, lands:'豊後', retainers:['吉弘統幸'], power:1,
                 events:['豊後一国のみを安堵される'], desc:'かつての九州探題も豊臣大名の一人となった。' },
      ryuzoji: { head:'龍造寺政家(鍋島直茂が実権)', castle:C.muranaka, lands:'肥前', retainers:['鍋島直茂','鍋島勝茂'], power:2,
                 events:['実権が鍋島氏へ移っていく'], desc:'沖田畷で隆信が討死して以来、鍋島氏が家政を主導。' },
      other:   { head:'—', castle:null, lands:'安房ほか', retainers:[], power:1,
                 events:['里見氏らが豊臣大名として存続'], desc:'個別に色分けしていない諸勢力。' }
    }
  },

  /* ========================= 1600年 ========================= */
  {
    year: 1600, era: '慶長5年', note: '関ヶ原の戦いの年',
    owners: {
      mutsu:'date', nanou:'uesugi', dewa:'mogami',
      musashi:'tokugawa', sagami:'tokugawa', izu:'tokugawa', kai:'tokugawa',
      shimousa:'tokugawa', kazusa:'tokugawa', kozuke:'tokugawa', shimotsuke:'tokugawa',
      hitachi:'satake',
      etchu:'maeda', noto:'maeda', kaga:'maeda',
      hoki:'mori', izumo:'mori', iwami:'mori', bingo:'mori',
      aki:'mori', suo:'mori', nagato:'mori',
      tosa:'chosokabe', hizen:'ryuzoji',
      hyuga:'shimazu', osumi:'shimazu', satsuma:'shimazu',
      echigo:'toyotomi', sado:'toyotomi', echizen:'toyotomi', wakasa:'toyotomi',
      shinano:'toyotomi', hida:'toyotomi', suruga:'toyotomi', totomi:'toyotomi',
      mikawa:'toyotomi', owari:'toyotomi', mino:'toyotomi', omi:'toyotomi',
      ise:'toyotomi', shima:'toyotomi', iga:'toyotomi',
      yamashiro:'toyotomi', yamato:'toyotomi', kawachi:'toyotomi', izumi:'toyotomi',
      settsu:'toyotomi', kii:'toyotomi', tanba:'toyotomi', tango:'toyotomi',
      tajima:'toyotomi', inaba:'toyotomi', harima:'toyotomi', mimasaka:'toyotomi',
      bizen:'toyotomi', bicchu:'toyotomi', awaji:'toyotomi', awa_s:'toyotomi',
      sanuki:'toyotomi', iyo:'toyotomi', chikuzen:'toyotomi', chikugo:'toyotomi',
      buzen:'toyotomi', bungo:'toyotomi', higo:'toyotomi'
    },
    clans: {
      tokugawa:{ head:'徳川家康', castle:C.edo, lands:'関東・甲斐', retainers:['本多忠勝','井伊直政','榊原康政','本多正信'], power:5,
                 events:['会津征伐に出陣','関ヶ原の戦いで西軍を破り、天下の実権を握る'], desc:'五大老筆頭。この年の勝利が江戸幕府へ直結する。' },
      toyotomi:{ head:'豊臣秀頼(石田三成ら西軍)', castle:C.osaka, lands:'畿内・西国の豊臣系大名領', retainers:['石田三成','大谷吉継','宇喜多秀家','小西行長'], power:4,
                 events:['三成らが家康弾劾の挙兵','関ヶ原で西軍が敗北し、豊臣の力が大きく削がれる'], desc:'秀吉没後、秀頼は幼く政権は分裂した。図は西軍寄りの大名領をまとめて表示。' },
      uesugi:  { head:'上杉景勝', castle:C.aizu, lands:'会津・出羽の一部(120万石)', retainers:['直江兼続','甘粕景継'], power:4,
                 events:['直江状で家康を挑発','長谷堂城で最上・伊達と戦う','戦後、米沢30万石へ減封'], desc:'会津へ移り西軍の東の柱となった。' },
      date:    { head:'伊達政宗', castle:C.sendai, lands:'陸奥', retainers:['片倉景綱','伊達成実'], power:3,
                 events:['東軍につき上杉領へ侵攻','白石城を攻略'], desc:'翌年、仙台に本拠を移し仙台藩の礎を築く。' },
      mogami:  { head:'最上義光', castle:C.yamagata, lands:'出羽', retainers:['志村光安','鮭延秀綱'], power:3,
                 events:['長谷堂城の戦いで上杉軍を防ぎきる','戦後、57万石に加増'], desc:'東軍として奮戦し、大幅に加増された。' },
      maeda:   { head:'前田利長', castle:C.kanazawa, lands:'加賀・能登・越中', retainers:['前田利政','村井長次'], power:4,
                 events:['東軍につき北陸の西軍勢力を制圧'], desc:'加賀百万石を確定させた。' },
      mori:    { head:'毛利輝元', castle:C.hiroshima, lands:'中国地方8か国', retainers:['吉川広家','安国寺恵瓊'], power:4,
                 events:['西軍の総大将に担がれ大坂城に入る','戦後、周防・長門2か国へ減封'], desc:'大坂を動かぬまま敗軍の将となった。' },
      satake:  { head:'佐竹義宣', castle:C.ota, lands:'常陸', retainers:['和田昭為','梶原政景'], power:3,
                 events:['旗幟を鮮明にせず、戦後に出羽秋田へ減転封'], desc:'三成との友誼と家中の事情に挟まれた。' },
      chosokabe:{ head:'長宗我部盛親', castle:{ name:'浦戸城', lon:133.55, lat:33.50 }, lands:'土佐', retainers:['久武親直','吉田政重'], power:2,
                 events:['西軍に属し、戦後に改易される'], desc:'関ヶ原ではほとんど戦わずに敗軍となり、家は取り潰された。' },
      shimazu: { head:'島津義弘', castle:C.uchijo, lands:'薩摩・大隅・日向の一部', retainers:['島津豊久','長寿院盛淳'], power:3,
                 events:['西軍として関ヶ原に布陣','敵中突破で戦場を離脱','所領は安堵される'], desc:'「島津の退き口」で名を上げ、本領を守り抜いた。' },
      ryuzoji: { head:'鍋島直茂・勝茂', castle:C.muranaka, lands:'肥前', retainers:['鍋島茂里'], power:2,
                 events:['西軍から東軍へ転じ、本領を安堵される'], desc:'実権は完全に鍋島氏へ移っていた。' },
      other:   { head:'—', castle:null, lands:'安房ほか', retainers:[], power:1,
                 events:['里見氏らが東軍に属す'], desc:'個別に色分けしていない諸勢力。' }
    }
  }
];
